export default {
"login": "Anand8216",
"id": 82560305,
"node_id": "MDQ6VXNlcjgyNTYwMzA1",
"avatar_url": "https://avatars.githubusercontent.com/u/82560305?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/Anand8216",
"html_url": "https://github.com/Anand8216",
"followers_url": "https://api.github.com/users/Anand8216/followers",
"following_url": "https://api.github.com/users/Anand8216/following{/other_user}",
"gists_url": "https://api.github.com/users/Anand8216/gists{/gist_id}",
"starred_url": "https://api.github.com/users/Anand8216/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/Anand8216/subscriptions",
"organizations_url": "https://api.github.com/users/Anand8216/orgs",
"repos_url": "https://api.github.com/users/Anand8216/repos",
"events_url": "https://api.github.com/users/Anand8216/events{/privacy}",
"received_events_url": "https://api.github.com/users/Anand8216/received_events",
"type": "User",
"site_admin": false,
"name": "Anand",
"company": null,
"blog": "",
"location": "Bihar",
"email": "anandshubham8216@gmail.com",
"hireable": "Yes",
"bio": "MERN Stack Developer",
"twitter_username": null,
"public_repos": 31,
"public_gists": 0,
"followers": 100,
"following": 52,
"created_at": "2021-04-15T04:03:22Z",
"updated_at": "2022-09-28T14:49:39Z"
};